  logging:
    level: DEBUG
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] - %(message)s"
    
  directories:
    workdir: ./seyoawe-community
    modules: ./seyoawe-community/modules
    workflows: ./seyoawe-community/workflows
    lifetimes: ./seyoawe-community/lifetimes
    logs: ./seyoawe-community/logs

  app:
    port: 8080
    poll_for_modules_on_startup: false # controlls the poller behavior. setting to true will override your modules every time the app boots
    ignored_workflow_dirs: # directories under directories.workflows that will be ignored by the engine
      - "samples"
      - "deprecated"
    base_url: http://localhost:8080

  module_dispatcher: 
    port: 8081
    url: http://localhost:8081/poll
    md5_strict: false
    customer_id: community
    secret_key: community
    modules_repo: https://github.com/yuribernstein/seyoawe-community.git
    modules_repo_access_key: ""
    modules_branch: main

  module_defaults:
    chatbot:
      provider: openai
      model: gpt-4
      temperature: 0.7
      api_key: ""

    api:
      timeout: 15
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{ context.default_api_token }}"
      blocking_defaults:
        poll_interval_seconds: 5
        timeout_minutes: 3

    email_module:
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_user: your@email.com
      smtp_pass: ""
      from_addr: "SeyoAWE Bot <your@email.com>"

    slack_module:
      webhook_url: "https://hooks.slack.com/services/<your_webhook_url>"

    git_module:
      github_token: ""